# PHP CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4
      - image: circleci/mysql:5.7

    branches:
      # Don't build from a branch with the `-built` suffix, to prevent endless loops of deploy scripts.
      ignore:
        - /^.*-built$/

    environment:
      - WP_TESTS_DIR: "/tmp/wordpress-tests-lib"
      - WP_CORE_DIR: "/tmp/wordpress/"
    steps:
      - checkout
      - run:
          name: "Setup Environment Variables"
          command: |
            echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> $BASH_ENV
            source /home/circleci/.bashrc
      - run:
          name: "Install Dependencies"
          command: |
            sudo apt-get update && sudo apt-get install subversion
            sudo docker-php-ext-install mysqli
            sudo apt-get update && sudo apt-get install default-mysql-client
            git submodule update --init
            sudo apt-get update -y
      - run:
          name: "Install composer dependencies"
          command: composer install -n -o
     # - run:
         # name: Run PHPCS
         # command: phpcs
      - run:
          name: "Run PHPUnit - Single Site"
          command: |
            rm -rf $WP_TESTS_DIR $WP_CORE_DIR
            bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest
            phpunit
